Estruturação do MVC
Maua-Dev/System_Maua_Front pull request #30
Opened 2021-07-29 14:52 UTC by FerdOliveira

Fixes #24

2021-08-06 02:52 UTC, FerdOliveira commented
![image](https://user-images.githubusercontent.com/79317347/128448806-c78f6d1e-9359-4196-a1e9-3e40ea5e72b6.png)

2021-08-06 21:53 UTC, DanielBranquinho requested changes
Arrumar conflito

2021-08-11 16:10 UTC, GabrielGodoy01 commented
Fix nos unittests, faltando o setAvisosAction no modulo Avisos e os tests do modulo HelpAluno

2021-08-11 16:11 UTC, GabrielGodoy01 requested changes
Fix nos unittests, faltando o setAvisosAction no modulo Avisos e os tests do modulo HelpAluno

2021-08-11 16:40 UTC, GabrielGodoy01 approved these changes
Aprovado

2021-08-11 16:42 UTC, FerdOliveira commented
![image](https://user-images.githubusercontent.com/79317347/129069058-dc885af1-4273-46a3-8054-44b9ba0c92cc.png)
Tela de Help

2021-08-11 16:42 UTC, FerdOliveira commented
![image](https://user-images.githubusercontent.com/79317347/129069141-2fdbaf6e-7c98-467f-896c-cfa02fb39560.png)
Tela de Avisos

2021-08-11 18:25 UTC, DanielBranquinho requested changes
Alinhar melhor a data com a box de cada aviso. A primeira está ruim

2021-08-11 21:00 UTC, FerdOliveira commented
![image](https://user-images.githubusercontent.com/79317347/129102647-de8b91cf-22b1-429c-b5e8-3f2e10019a69.png)
uptade

2021-08-11 21:01 UTC, DanielBranquinho approved these changes

2021-08-11 21:02 UTC, merged