Gustavo crs/issue6
Maua-Dev/System_Maua_Front pull request #38
Opened 2021-08-09 20:30 UTC by Gustavo-CRS

2021-08-17 20:28 UTC, GabrielGodoy01 requested changes
Adicionar responsividade a tela e avaliar com o PO o aviso de senha inválida, o mais usado é: "E-mail ou senha inválidos".

2021-08-20 20:04 UTC, GabrielGodoy01 approved these changes

2021-08-20 23:13 UTC, Gustavo-CRS commented
![image](https://user-images.githubusercontent.com/51282187/130301686-59ac1188-7cc1-4f6d-8789-65aec0d909cd.png)

2021-08-22 15:50 UTC, DanielBranquinho approved these changes

2021-08-22 15:50 UTC, merged