Caiogtoledo/issue8
Maua-Dev/System_Maua_Front pull request #51
Opened 2021-08-19 02:19 UTC by caiogtoledo

2021-08-28 22:47 UTC, caiogtoledo commented
Tempo gasto com o desenvolvimento: 7:30

2021-08-29 20:06 UTC, caiogtoledo commented
<img width="264" alt="Captura de Tela 2021-08-29 às 17 06 07" src="https://user-images.githubusercontent.com/63592244/131263933-789e758c-cc71-4632-b26b-88a6061fd5ec.png">

2021-08-30 20:48 UTC, GabrielGodoy01 requested changes
1.  medias_page -> desnecessário o uso do leadingWidget, combinamos de usar o Modular.to.navigate
2. medias_controller -> bom costume criar um newInstance para os models MediasModel e FiltrosMediasModel
3. Remover print do medias_repository e opcao_chip_controller, usa o test unitario pra testes
4. Dar uma olhada nesse medias_controller, funções de escolheAno e toggleOpcao

2021-09-02 11:07 UTC, GabrielGodoy01 approved these changes

2021-09-07 13:07 UTC, merged