Gustavo-CRS/[FM-26] - Pull request de oportunidades abertas finalizadas
Maua-Dev/System_Maua_Front pull request #75
Opened 2021-09-23 19:38 UTC by Gustavo-CRS

2021-09-23 19:42 UTC, Gustavo-CRS commented
![image](https://user-images.githubusercontent.com/51282187/134573181-a1f105d3-b574-4b0b-bbe1-a9cc2f2e361c.png)

2021-09-23 20:43 UTC, GabrielGodoy01 requested changes
- Remover linha 27 desnecessária do help_module;
- Ajustar nome do arquivo faqcard_widget para o pattern
- Ajustar o nome do arquivo i_oportunidade_repository para o pattern
- Organizar o modulo de páginas dentro do help-intercambio
- Arrumar comentário do teste do help_intercambio_module
- A página é scrollable? Se sim, ok, se não, pode dar erros no futuro, então fix

2021-09-30 02:25 UTC, GabrielGodoy01 approved these changes

2021-10-11 21:38 UTC, DanielBranquinho requested changes
Resolver conflitos

2021-10-11 23:23 UTC, GabrielGodoy01 approved these changes

2021-10-11 23:31 UTC, DanielBranquinho approved these changes

2021-10-11 23:32 UTC, merged