[FM-19] - Lista de Videos tutoriais
Maua-Dev/System_Maua_Front pull request #79
Opened 2021-09-30 02:14 UTC by Felipe-16

2021-09-30 03:05 UTC, GabrielGodoy01 requested changes
Na page, provavel que tenha uma formatação melhor para o texto '''Abaixo está uma lista de 
videos para se assistirem em 
relação ao melhor
aproveitamento da nossa 
plataforma'''

Fazer os unit tests do modulo

2021-09-30 03:39 UTC, GabrielGodoy01 approved these changes

2021-10-04 16:52 UTC, DanielBranquinho approved these changes

2021-10-04 16:52 UTC, DanielBranquinho requested changes
Arrumar conflito

2021-10-06 23:40 UTC, GabrielGodoy01 approved these changes

2021-10-07 00:01 UTC, DanielBranquinho approved these changes

2021-10-08 11:41 UTC, merged